// The Catalog: every command documented in the CAS Reference Guide, with the
// syntax TI prints for it. Generated from research/signatures.json, which was
// extracted from the guide itself.

export const CATALOG = [
  { name: "abs", sig: "abs(Expr1)" },
  { name: "amortTbl", sig: "amortTbl(NPmt,N,I,PV, [Pmt], [FV]," },
  { name: "angle", sig: "angle(Expr1)" },
  { name: "ANOVA", sig: "ANOVAList1,List2[,List3,...,List20][,Flag]" },
  { name: "ANOVA2way", sig: "ANOVA2wayList1,List2[,List3,…,List10]" },
  { name: "approx", sig: "approx(Expr1)" },
  { name: "approxRational", sig: "approxRational(Expr[,Tol])" },
  { name: "arcLen", sig: "arcLen(Expr1,Var,Start,End)" },
  { name: "augment", sig: "augment(List1,List2)" },
  { name: "avgRC", sig: "avgRC(Expr1,Var[=Value] [,Step])" },
  { name: "bal", sig: "bal(NPmt,N,I,PV,[Pmt], [FV], [PpY]," },
  { name: "binomCdf", sig: "binomCdf(n,p)" },
  { name: "binomPdf", sig: "binomPdf(n,p)" },
  { name: "centralDiff", sig: "centralDiff(Expr1,Var[=Value][,Step])" },
  { name: "cFactor", sig: "cFactor(Expr1[,Var])" },
  { name: "char", sig: "char(Integer)" },
  { name: "charPoly", sig: "charPoly(squareMatrix,Var)" },
  { name: "Clear", sig: "Clearx,y,width,height" },
  { name: "ClearAZ", sig: "ClearAZ" },
  { name: "ClrErr", sig: "ClrErr" },
  { name: "colAugment", sig: "colAugment(Matrix1,Matrix2)" },
  { name: "colDim", sig: "colDim(Matrix)" },
  { name: "colNorm", sig: "colNorm(Matrix)" },
  { name: "comDenom", sig: "comDenom(Expr1[,Var])" },
  { name: "completeSquare", sig: "completeSquare(ExprOrEqn,Var)" },
  { name: "conj", sig: "conj(Expr1)" },
  { name: "constructMat", sig: "constructMat" },
  { name: "CopyVar", sig: "CopyVarVar1,Var2" },
  { name: "corrMat", sig: "corrMat(List1,List2[,…[,List20]])" },
  { name: "cos", sig: "►cosreducesallpowersof" },
  { name: "cosh", sig: "cosh(Expr1)" },
  { name: "coth", sig: "coth(Expr1)" },
  { name: "count", sig: "count(Value1orList1[,Value2orList2" },
  { name: "countif", sig: "countif(List,Criteria)" },
  { name: "cPolyRoots", sig: "cPolyRoots(Poly,Var)" },
  { name: "crossP", sig: "crossP(List1,List2)" },
  { name: "csch", sig: "csch(Expr1)" },
  { name: "cSolve", sig: "cSolve(Equation,Var)" },
  { name: "CubicReg", sig: "CubicRegX,Y[, [Freq] [,Category," },
  { name: "cumulativeSum", sig: "cumulativeSum(List1)" },
  { name: "Cycle", sig: "Cycle" },
  { name: "cZeros", sig: "cZeros(Expr,Var)" },
  { name: "dbd", sig: "dbd(date1,date2)" },
  { name: "Define", sig: "DefineVar=Expression" },
  { name: "DefineLibPriv", sig: "DefineLibPrivVar=Expression" },
  { name: "DefineLibPub", sig: "DefineLibPubVar=Expression" },
  { name: "DelVar", sig: "DelVarVar1[,Var2] [,Var3] ..." },
  { name: "delVoid", sig: "delVoid(List1)" },
  { name: "deSolve", sig: "deSolve(1stOr2ndOrderODE,Var," },
  { name: "det", sig: "det(squareMatrix[,Tolerance])" },
  { name: "diag", sig: "diag(List)" },
  { name: "dim", sig: "dim(List)" },
  { name: "Disp", sig: "DispexprOrString1[,exprOrString2] ..." },
  { name: "DispAt", sig: "DispAtint,expr1[,expr2...] ..." },
  { name: "domain", sig: "domain(Expr1,Var)" },
  { name: "dominantTerm", sig: "dominantTerm(Expr1,Var[,Point])" },
  { name: "dotP", sig: "dotP(List1,List2)" },
  { name: "DrawArc", sig: "DrawArcx,y,width,height,startAngle,arcAngle" },
  { name: "DrawCircle", sig: "DrawCirclex,y,radius" },
  { name: "DrawLine", sig: "DrawLinex1,y1,x2,y2" },
  { name: "DrawPoly", sig: "DrawPolyxlist,ylist" },
  { name: "DrawRect", sig: "DrawRectx,y,width,height" },
  { name: "DrawText", sig: "DrawTextx,y,exprOrString1[,exprOrString2]..." },
  { name: "eff", sig: "eff(nominalRate,CpY)" },
  { name: "eigVc", sig: "eigVc(squareMatrix)" },
  { name: "eigVl", sig: "eigVl(squareMatrix)" },
  { name: "ElseIf", sig: "ElseIfBooleanExpr2Then" },
  { name: "euler", sig: "euler(Expr,Var,depVar, {Var0,VarMax}," },
  { name: "exact", sig: "exact(Expr1[,Tolerance])" },
  { name: "Exit", sig: "Exit" },
  { name: "exp", sig: "exponentiale. Thisisadisplayconversion" },
  { name: "expand", sig: "expand(Expr1[,Var])" },
  { name: "expr", sig: "expr(String)" },
  { name: "ExpReg", sig: "ExpRegX,Y [, [Freq] [,Category,Include]]" },
  { name: "factor", sig: "factor(Expr1[,Var])" },
  { name: "FCdf", sig: "FCdf" },
  { name: "Fill", sig: "FillExpr,matrixVar" },
  { name: "FillArc", sig: "FillArcx,y,width,heightstartAngle,arcAngle" },
  { name: "FillCircle", sig: "FillCirclex,y,radius" },
  { name: "FillPoly", sig: "FillPolyxlist,ylist" },
  { name: "FillRect", sig: "FillRectx,y,width,height" },
  { name: "FiveNumSummary", sig: "FiveNumSummaryX[,[Freq]" },
  { name: "floor", sig: "floor(Expr1)" },
  { name: "fMax", sig: "fMax(Expr,Var)" },
  { name: "fMin", sig: "fMin(Expr,Var)" },
  { name: "For", sig: "ForVar,Low,High[,Step]" },
  { name: "format", sig: "format(Expr[,formatString])" },
  { name: "fPart", sig: "fPart(Expr1)" },
  { name: "FPdf", sig: "FPdf(XVal,dfNumer,dfDenom)" },
  { name: "frequency", sig: "frequency(List1,binsList)" },
  { name: "FTest_2Samp", sig: "FTest_2SampList1,List2[,Freq1[,Freq2" },
  { name: "Func", sig: "Func" },
  { name: "gcd", sig: "gcd(Number1,Number2)" },
  { name: "geomCdf", sig: "geomCdf(p,lowBound,upBound)" },
  { name: "geomPdf", sig: "geomPdf(p,XVal)" },
  { name: "getDenom", sig: "getDenom(Expr1)" },
  { name: "getKey", sig: "getKey([0|1])" },
  { name: "getLangInfo", sig: "getLangInfo()" },
  { name: "getLockInfo", sig: "getLockInfo(Var)" },
  { name: "getMode", sig: "getMode(ModeNameInteger)" },
  { name: "getNum", sig: "getNum(Expr1)" },
  { name: "getPlatform", sig: "getPlatform()" },
  { name: "getType", sig: "getType(var)" },
  { name: "getVarInfo", sig: "getVarInfo()" },
  { name: "Goto", sig: "GotolabelName" },
  { name: "identity", sig: "identity(Integer)" },
  { name: "If", sig: "IfBooleanExprStatement" },
  { name: "ifFn", sig: "ifFn(BooleanExpr,Value_If_true[,Value_If_false[,Value_If_unknown]])" },
  { name: "imag", sig: "imag(Expr1)" },
  { name: "impDif", sig: "impDif(Equation,Var,dependVar[,Ord])" },
  { name: "inString", sig: "inString(srcString,subString[,Start])" },
  { name: "int", sig: "int(Expr)" },
  { name: "intDiv", sig: "intDiv(Number1,Number2)" },
  { name: "interpolate", sig: "interpolate(xValue,xList,yList," },
  { name: "invBinom", sig: "invBinom" },
  { name: "invBinomN", sig: "invBinomN(CumulativeProb,Prob," },
  { name: "invF", sig: "invF(Area,dfNumer,dfDenom)" },
  { name: "invNorm", sig: "invNorm(Area[,μ[,σ]])" },
  { name: "invt", sig: "invt(Area,df)" },
  { name: "invχ2", sig: "invχ2(Area,df)" },
  { name: "iPart", sig: "iPart(Number)" },
  { name: "irr", sig: "irr(CF0,CFList[,CFFreq])" },
  { name: "isPrime", sig: "isPrime(Number)" },
  { name: "isVoid", sig: "isVoid(Var)" },
  { name: "Lbl", sig: "LbllabelName" },
  { name: "lcm", sig: "lcm(Number1,Number2)" },
  { name: "left", sig: "left(sourceString[,Num])" },
  { name: "libShortcut", sig: "libShortcut(LibNameString," },
  { name: "LinRegBx", sig: "LinRegBxX,Y[,[Freq][,Category,Include]]" },
  { name: "LinRegMx", sig: "LinRegMxX,Y[,[Freq][,Category,Include]]" },
  { name: "LinRegtIntervals", sig: "LinRegtIntervalsX,Y[,F[,0[,CLev]]]" },
  { name: "LinRegtTest", sig: "LinRegtTestX,Y[,Freq[,Hypoth]]" },
  { name: "linSolve", sig: "linSolve( SystemOfLinearEqns,Var1," },
  { name: "ln", sig: "ln() /ukeys" },
  { name: "LnReg", sig: "LnRegX,Y[, [Freq] [,Category,Include]]" },
  { name: "Local", sig: "LocalVar1[,Var2] [,Var3] ..." },
  { name: "Lock", sig: "LockVar1[,Var2] [,Var3] ..." },
  { name: "Logistic", sig: "LogisticX,Y[, [Freq] [,Category,Include]]" },
  { name: "LogisticD", sig: "LogisticDX,Y[, [Iterations] , [Freq] [," },
  { name: "Loop", sig: "Loop" },
  { name: "LU", sig: "LUMatrix,lMatrix,uMatrix,pMatrix[,Tol]" },
  { name: "max", sig: "max(Expr1,Expr2)" },
  { name: "mean", sig: "mean(List[,freqList])" },
  { name: "median", sig: "median(List[,freqList])" },
  { name: "MedMed", sig: "MedMedX,Y[,Freq] [,Category,Include]]" },
  { name: "mid", sig: "mid(sourceString,Start[,Count])" },
  { name: "min", sig: "min(Expr1,Expr2)" },
  { name: "mirr", sig: "mirr" },
  { name: "mod", sig: "mod(Expr1,Expr2)" },
  { name: "mRow", sig: "mRow(Expr,Matrix1,Index)" },
  { name: "mRowAdd", sig: "mRowAdd(Expr,Matrix1,Index1,Index2)" },
  { name: "MultReg", sig: "MultRegY,X1[,X2[,X3,…[,X10]]]" },
  { name: "MultRegIntervals", sig: "MultRegIntervalsY,X1[,X2[,X3,…[," },
  { name: "MultRegTests", sig: "MultRegTestsY,X1[,X2[,X3,…[,X10]]]" },
  { name: "nCr", sig: "nCr(Expr1,Expr2)" },
  { name: "nDerivative", sig: "nDerivative(Expr1,Var=Value[,Order])" },
  { name: "newList", sig: "newList(numElements)" },
  { name: "newMat", sig: "newMat(numRows,numColumns)" },
  { name: "nfMax", sig: "nfMax(Expr,Var)" },
  { name: "nfMin", sig: "nfMin(Expr,Var)" },
  { name: "nInt", sig: "nInt(Expr1,Var,Lower,Upper)" },
  { name: "nom", sig: "nom(effectiveRate,CpY)" },
  { name: "norm", sig: "norm(Matrix)" },
  { name: "normalLine", sig: "normalLine(Expr1,Var,Point)" },
  { name: "normCdf", sig: "normCdf(lowBound,upBound[,μ[,σ]])" },
  { name: "normPdf", sig: "normPdf(XVal[,μ[,σ]])" },
  { name: "not", sig: "notBooleanExpr" },
  { name: "nPr", sig: "nPr(Expr1,Expr2)" },
  { name: "npv", sig: "npv(InterestRate,CFO,CFList[,CFFreq])" },
  { name: "nSolve", sig: "nSolve(Equation,Var[=Guess])" },
  { name: "OneVar", sig: "OneVar[1,]X[,[Freq][,Category,Include]]" },
  { name: "ord", sig: "ord(String)" },
  { name: "PaintBuffer", sig: "PaintBuffer" },
  { name: "PassErr", sig: "PassErr" },
  { name: "piecewise", sig: "piecewise(Expr1[,Cond1[,Expr2[,Cond2" },
  { name: "PlotXY", sig: "PlotXYx,y,shape" },
  { name: "poissCdf", sig: "poissCdf(λ,lowBound,upBound)" },
  { name: "poissPdf", sig: "poissPdf(λ,XVal)" },
  { name: "polyCoeffs", sig: "polyCoeffs(Poly[,Var])" },
  { name: "polyDegree", sig: "polyDegree(Poly[,Var])" },
  { name: "polyEval", sig: "polyEval(List1,Expr1)" },
  { name: "polyGcd", sig: "polyGcd(Expr1,Expr2)" },
  { name: "polyQuotient", sig: "polyQuotient(Poly1,Poly2[,Var])" },
  { name: "polyRemainder", sig: "polyRemainder(Poly1,Poly2[,Var])" },
  { name: "polyRoots", sig: "polyRoots(Poly,Var)" },
  { name: "PowerReg", sig: "PowerRegX,Y[,Freq][,Category,Include]]" },
  { name: "Prgm", sig: "Prgm" },
  { name: "product", sig: "product(List[,Start[,End]])" },
  { name: "propFrac", sig: "propFrac(Expr1[,Var])" },
  { name: "QR", sig: "QRMatrix,qMatrix,rMatrix[,Tol]" },
  { name: "QuadReg", sig: "QuadRegX,Y[,Freq][,Category,Include]]" },
  { name: "QuartReg", sig: "QuartRegX,Y[,Freq][,Category,Include]]" },
  { name: "rand", sig: "rand()" },
  { name: "randBin", sig: "randBin(n,p)" },
  { name: "randInt", sig: "randInt" },
  { name: "randMat", sig: "randMat(numRows,numColumns)" },
  { name: "randNorm", sig: "randNorm(μ, σ)" },
  { name: "randPoly", sig: "randPoly(Var,Order)" },
  { name: "randSamp", sig: "randSamp(List,#Trials[,noRepl])" },
  { name: "RandSeed", sig: "RandSeedNumber" },
  { name: "real", sig: "real(Expr1)" },
  { name: "ref", sig: "ref(Matrix1[,Tol])" },
  { name: "RefreshProbeVars", sig: "RefreshProbeVars" },
  { name: "remain", sig: "remain(Expr1,Expr2)" },
  { name: "Request", sig: "RequestpromptString,var[, DispFlag" },
  { name: "RequestStr", sig: "RequestStrpromptString,var[,DispFlag]" },
  { name: "Return", sig: "Return[Expr]" },
  { name: "right", sig: "right(List1[,Num])" },
  { name: "rk23", sig: "rk23(Expr,Var,depVar, {Var0,VarMax}," },
  { name: "root", sig: "root(Expr)" },
  { name: "rotate", sig: "rotate(Integer1[,#ofRotations])" },
  { name: "round", sig: "round(Expr1[,digits])" },
  { name: "rowAdd", sig: "rowAdd(Matrix1,rIndex1,rIndex2)" },
  { name: "rowDim", sig: "rowDim(Matrix)" },
  { name: "rowNorm", sig: "rowNorm(Matrix)" },
  { name: "rowSwap", sig: "rowSwap(Matrix1,rIndex1,rIndex2)" },
  { name: "rref", sig: "rref(Matrix1[,Tol])" },
  { name: "sech", sig: "sech(Expr1)" },
  { name: "seq", sig: "seq(Expr,Var,Low,High[,Step])" },
  { name: "seqGen", sig: "seqGen(Expr,Var,depVar, {Var0," },
  { name: "seqn", sig: "seqn(Expr(u,n[,ListOfInitTerms[,nMax[," },
  { name: "series", sig: "series(Expr1,Var,Order[,Point])" },
  { name: "SetColor", sig: "SetColor" },
  { name: "setMode", sig: "setMode(modeNameInteger," },
  { name: "SetPen", sig: "SetPen" },
  { name: "SetWindow", sig: "SetWindow" },
  { name: "shift", sig: "shift(Integer1[,#ofShifts])" },
  { name: "sign", sig: "sign(Expr1)" },
  { name: "simult", sig: "simult(coeffMatrix,constVector[,Tol])" },
  { name: "sin", sig: "►sinreducesallpowersof" },
  { name: "sinh", sig: "sinh(Expr1)" },
  { name: "SinReg", sig: "SinRegX,Y[, [Iterations],[Period][," },
  { name: "solve", sig: "solve(Equation,Var)" },
  { name: "SortA", sig: "SortAList1[,List2] [,List3]..." },
  { name: "SortD", sig: "SortDList1[,List2][,List3]..." },
  { name: "sqrt", sig: "sqrt(Expr1)" },
  { name: "stDevPop", sig: "stDevPop(List[,freqList])" },
  { name: "stDevSamp", sig: "stDevSamp(List[,freqList])" },
  { name: "Stop", sig: "Stop" },
  { name: "string", sig: "string(Expr)" },
  { name: "subMat", sig: "subMat(Matrix1[,startRow][,startCol][," },
  { name: "sum", sig: "sum(List[,Start[,End]])" },
  { name: "sumIf", sig: "sumIf(List,Criteria[,SumList])" },
  { name: "system", sig: "system(Eqn1[,Eqn2[,Eqn3[, ...]]])" },
  { name: "tangentLine", sig: "tangentLine(Expr1,Var,Point)" },
  { name: "tanh", sig: "tanh(Expr1)" },
  { name: "taylor", sig: "taylor(Expr1,Var,Order[,Point])" },
  { name: "tCdf", sig: "tCdf(lowBound,upBound,df)" },
  { name: "tCollect", sig: "tCollect(Expr1)" },
  { name: "tExpand", sig: "tExpand(Expr1)" },
  { name: "Text", sig: "TextpromptString[,DispFlag]" },
  { name: "tInterval", sig: "tIntervalList[,Freq[,CLevel]]" },
  { name: "tInterval_2Samp", sig: "tInterval_2SampList1,List2[,Freq1[,Freq2" },
  { name: "tmpCnv", sig: "tmpCnv(Expr_°tempUnit, _°tempUnit2)" },
  { name: "tPdf", sig: "tPdf(XVal,df)" },
  { name: "trace", sig: "trace(squareMatrix)" },
  { name: "Try", sig: "Try" },
  { name: "tTest", sig: "tTestμ0,List[,Freq[,Hypoth]]" },
  { name: "tTest_2Samp", sig: "tTest_2SampList1,List2[,Freq1[,Freq2" },
  { name: "tvmFV", sig: "tvmFV(N,I,PV,Pmt,[PpY],[CpY],[PmtAt])" },
  { name: "tvmI", sig: "tvmI(N,PV,Pmt,FV,[PpY],[CpY],[PmtAt])" },
  { name: "tvmN", sig: "tvmN(I,PV,Pmt,FV,[PpY],[CpY],[PmtAt])" },
  { name: "tvmPmt", sig: "tvmPmt(N,I,PV,FV,[PpY],[CpY],[PmtAt])" },
  { name: "tvmPV", sig: "tvmPV(N,I,Pmt,FV,[PpY],[CpY],[PmtAt])" },
  { name: "TwoVar", sig: "TwoVarX,Y[, [Freq][,Category,Include]]" },
  { name: "unitV", sig: "unitV(Vector1)" },
  { name: "unLock", sig: "unLockVar1[,Var2] [,Var3] ..." },
  { name: "UseBuffer", sig: "UseBuffer" },
  { name: "varPop", sig: "varPop(List[,freqList])" },
  { name: "varSamp", sig: "varSamp(List[,freqList])" },
  { name: "Wait", sig: "WaittimeInSeconds" },
  { name: "warnCodes", sig: "warnCodes(Expr1,StatusVar)" },
  { name: "when", sig: "when(Condition,trueResult[,falseResult]" },
  { name: "While", sig: "WhileCondition Block" },
  { name: "xor", sig: "xorBooleanList2returnsBooleanlistBooleanMatrix1" },
  { name: "zeros", sig: "zeros(Expr,Var)" },
  { name: "zInterval", sig: "zIntervalσ,List[,Freq[,CLevel]]" },
  { name: "zInterval_1Prop", sig: "zInterval_1Propx,n[,CLevel]" },
  { name: "zInterval_2Prop", sig: "zInterval_2Propx1,n1,x2,n2[,CLevel]" },
  { name: "zInterval_2Samp", sig: "zInterval_2Sampσ1,σ2 ,List1,List2[,Freq1" },
  { name: "zTest", sig: "zTestμ0,σ,List,[Freq[,Hypoth]]" },
  { name: "zTest_2Prop", sig: "zTest_2Propx1,n1,x2,n2[,Hypoth]" },
  { name: "zTest_2Samp", sig: "zTest_2Sampσ1,σ2 ,List1,List2[,Freq1" },
  { name: "ΔList", sig: "ΔList(List1)" },
  { name: "ΔtmpCnv", sig: "ΔtmpCnv(Expr_°tempUnit, _°tempUnit2)" },
  { name: "χ22way", sig: "χ22wayobsMatrix" },
  { name: "χ2Cdf", sig: "χ2Cdf(lowBound,upBound,df)" },
  { name: "χ2GOF", sig: "χ2GOFobsList,expList,df" },
  { name: "χ2Pdf", sig: "χ2Pdf(XVal,df)" },
];
